### ISSUE TITLE
WebUI Not working - Internal Error 500

### ISSUE THREAD

**Issue by qy2009** [dreulavelle/iceberg#344]
Hi,

I just tried to run the docker, but it said 500 internal error? 

here is the log

Starting Container with 1000:1000 permissions...
Container Initialization complete.
Starting backend...
Starting frontend...
Listening on 0.0.0.0:3000
2024-06-04 18:04:50 | 🤖 PROGRAM   | program.start - Iceberg v0.6.3 starting!
2024-06-04 18:04:50 | ⚠️  WARNING   | overseerr.validate - Overseerr is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | plex_watchlist.validate - Plex Watchlists is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | listrr.validate - Listrr is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | mdblist.validate - Mdblist is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | trakt.validate - Trakt is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | annatar.validate - Annatar is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | torrentio.validate - Torrentio is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | orionoid.validate - Orionoid is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | jackett.validate - Jackett is set to disabled.
2024-06-04 18:04:50 | ⚠️  WARNING   | torbox.validate - TorBox Scraper is set to disabled
2024-06-04 18:04:51 | ❌ ERROR     | symlink.validate - rclone_path does not exist: /mnt/zurg/__all__
2024-06-04 18:04:51 | ❌ ERROR     | symlink.__init__ - Symlink initialization failed due to invalid configuration.
2024-06-04 18:04:51 | ❌ ERROR     | plex.validate - Plex Updater token is not set, this is required!
2024-06-04 18:04:51 | ⚠️  WARNING   | realdebrid.validate - Real-Debrid is set to disabled
2024-06-04 18:04:51 | ❌ ERROR     | program.start - Failed to initialize services: [Errno 2] No such file or directory: '/mnt/library'
Traceback (most recent call last):
  File "/iceberg/backend/program/program.py", line 104, in start
    self.initialize_services()
  File "/iceberg/backend/program/program.py", line 64, in initialize_services
    SymlinkLibrary: SymlinkLibrary(),
  File "/iceberg/backend/program/libraries/symlink.py", line 15, in __init__
    self.initialized = self.validate()
  File "/iceberg/backend/program/libraries/symlink.py", line 30, in validate
    available_dirs = ", ".join(os.listdir(library_path))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/library'
2024-06-04 18:04:51 | 🤖 PROGRAM   | program.start - ----------------------------------------------
2024-06-04 18:04:51 | 🤖 PROGRAM   | program.start - Iceberg is waiting for configuration to start!
2024-06-04 18:04:51 | 🤖 PROGRAM   | program.start - ----------------------------------------------
2024-06-04 18:04:51 | ❌ ERROR     | main.<module> - Program failed to initialize: 'Program' object has no attribute 'library_services'
2024-06-04 18:04:51 |  CRITICAL  | main.<module> - Server has been stopped
TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:8080
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8080
  }
}

**Comment by dreulavelle** [comment]
yes, the frontend is under development :)
