### ISSUE TITLE
[BUG] Plex Watchlist Issue: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by dreulavelle** [dreulavelle/iceberg#54]
```sh
Starting Container with 1000:1000 permissions...
Initialization complete. Executing main process...
[2023-12-18 14:29:39 | DEBUG] <settings.load> - Settings loaded from /iceberg/data/settings.json
[2023-12-18 14:29:40 | DEBUG] <settings.get> - Get (mdblist) returned: {'lists': ['29073'], 'api_key': 'REDACTED', 'update_interval': 80}
[2023-12-18 14:29:41 | DEBUG] <settings.get> - Get (overseerr) returned: {'url': 'http://overseerr:5055', 'api_key': 'REDACTED'}
[2023-12-18 14:29:41 | DEBUG] <settings.get> - Get (plex) returned: {'user': 'REDACTED', 'token': 'REDACTED', 'url': 'http://192.168.1.154:32400', 'watchlist': 'https://rss.plex.tv/9b11874b-f7f5-476d-83ce-REDACTED'}
[2023-12-18 14:29:42 | INFO] <mdblist.run> - Added 50 items
[2023-12-18 14:29:42 | INFO] <overseerr.run> - Added 7 items
[2023-12-18 14:29:43 | DEBUG] <plex_watchlist._get_items_from_plex_watchlist> - Found 50 items
Traceback (most recent call last):
  File "/iceberg/backend/main.py", line 22, in <module>
    app.program = Program()
                  ^^^^^^^^^
  File "/iceberg/backend/program/__init__.py", line 64, in __init__
    Content(self.media_items),  # Content must be first
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/iceberg/backend/program/content/__init__.py", line 28, in __init__
    service.run()
  File "/iceberg/backend/program/content/plex_watchlist.py", line 41, in run
    container = self.updater.create_items(new_items)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/iceberg/backend/program/updaters/trakt.py", line 36, in create_items
    get_items.append(item)
  File "/iceberg/backend/program/media.py", line 289, in append
    self.sort("requested_at", True)
  File "/iceberg/backend/program/media.py", line 279, in sort
    self.items.sort(key=lambda item: item.get(by), reverse=reverse)
  File "/iceberg/backend/program/media.py", line 279, in <lambda>
    self.items.sort(key=lambda item: item.get(by), reverse=reverse)
                                     ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dreulavelle** [comment]
Also need to add watchlist rss feed to be redacted from logs.
