### ISSUE TITLE
[BUG] tt5321682 causes a crash

### ISSUE THREAD

**Issue by activ** [dreulavelle/iceberg#97]
Wit the help of Gb I added extra logging and found that tt5321682 crashes iceberg consitently.

```sh
[2023-12-29 12:04:51 | DEBUG] <trakt._map_item_from_data> - tt5321682
Iceberg  | Traceback (most recent call last):
Iceberg  |   File "/iceberg/backend/main.py", line 22, in <module>
Iceberg  |     app.program = Program()
Iceberg  |                   ^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/__init__.py", line 59, in __init__
Iceberg  |     Content(self.media_items),  # Content must be first
Iceberg  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/content/__init__.py", line 28, in __init__
Iceberg  |     service.run()
Iceberg  |   File "/iceberg/backend/program/content/overseerr.py", line 40, in run
Iceberg  |     container = self.updater.create_items(new_items)
Iceberg  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/updaters/trakt.py", line 27, in create_items
Iceberg  |     item = self._create_item(imdb_id)
Iceberg  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/updaters/trakt.py", line 43, in _create_item
Iceberg  |     item = create_item_from_imdb_id(imdb_id)
Iceberg  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/updaters/trakt.py", line 131, in create_item_from_imdb_id
Iceberg  |     return _map_item_from_data(data, media_type)
Iceberg  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  |   File "/iceberg/backend/program/updaters/trakt.py", line 93, in _map_item_from_data
Iceberg  |     item["number"] = getattr(data, "number")
Iceberg  |                      ^^^^^^^^^^^^^^^^^^^^^^^
Iceberg  | AttributeError: 'types.SimpleNamespace' object has no attribute 'number'
```

**Comment by dreulavelle** [comment]
Iceberg doesnt handle Specials very well :/

**Comment by dreulavelle** [comment]
https://torrentio.strem.fun/qualityfilter=other,scr,cam,unknown/stream/series/tt5321682:1:1.json

Episodes show up on Torrentio under that imdb id. Really weird its throwing an error. Was old pkl files involved?

**Comment by activ** [comment]
Nope, no old pkl. Persisted even after removing the pkl’s. I did not try adding it again after removing overseerr’s database though, maybe something was wrong with it on the overseer side?

**Comment by dreulavelle** [comment]
This needs to get looked at @Gaisberg 

We suck at retrieving specials for items..

**Comment by dreulavelle** [comment]
This has been fixed in the latest update. Adds the item correctly now.
